### PR TITLE
Clarify that mco is not a hard requirement

### PR DESCRIPTION
**Pull request by binford2k**

### CODE REVIEW

**Comment by qralston** [comment]
I think this change helps clarify that mco is only a requirement if you specially want to use mco to update multiple masters, and that nothing stops you from using some other mechanism to update multiple servers.

**Comment by bastelfreak** [comment]
@binford2k @adrienthebo was that label intentional? Otherwise I'm fine with merging it.

**Comment by dhollinger** [comment]
Can we get the mcollective-client gem removed as runtime dependency added  in this PR?

**Comment by qralston** [comment]
> Can we get the mcollective-client gem removed as runtime dependency added in this PR?

+1 to this.

I don't want to install the mcollective-client gem if I don't need it, because it attempts to overwrite `/opt/puppetlabs/puppet/bin/mco` from the `puppet-agent` RPM package, which will then cause `rpm --verify puppet-agent` to throw checksum errors for `/opt/puppetlabs/puppet/bin/mco`.

**Comment by dhollinger** [comment]
@binford2k we'll have to add the mcollective-client gem as a development dependency as the tests utilize mcollective (sorry, didn't even think about that).

**Pull request merged**
